[SUBTITLE]
00:00:12.25,00:00:15.12
Wie ist es; wie können wird diese

00:00:15.22,00:00:18.31
Virenflora untersuchen, die uns umgibt

00:00:18.41,00:00:19.93
um die Medizin zu unterstützen?

00:00:20.03,00:00:24.12
Wie können wir unser kumulatives Wissen der Virologie umsetzen

00:00:24.22,00:00:28.08
in einen einfachen, tragbaren, einzelnen diagnostischen Nachweistest?

00:00:28.18,00:00:29.83
Ich möchte alles was wir zur Zeit kennen

00:00:29.93,00:00:33.66
über das Aufspüren von Viren und das Spektrum von Viren, die es draußen gibt,

00:00:33.76,00:00:36.08
in, sagen wir, einen kleinen Chip umsetzen.

00:00:36.18,00:00:41.18
Als wir begannen über dieses Projet nachzudenken, wie wir einen einzelnen diagnostischen Test,

00:00:41.28,00:00:44.21
um alle Pathogene simultan zu überprüfen, machen könnten.

00:00:44.31,00:00:46.31
Nun, es gibt einige Probleme mit dieser Idee.

00:00:46.41,00:00:47.41
Zuallererst,

00:00:47.51,00:00:50.20
Viren sind sehr komplex

00:00:50.35,00:00:52.52
aber sie entwickeln sich auch

00:00:52.62,00:00:54.00
sehr schnell.

00:00:54.10,00:00:56.25
Dies ist ein Picornavirus. Picornaviren:

00:00:56.35,00:00:59.33
das sind Dinge, die die gemeine Kälte und Polio beinhalten.

00:00:59.43,00:01:02.13
Solche Dinge eben. Sie sehen gerade die äußere Hülle des Virus

00:01:02.23,00:01:06.62
und die gelbe Farbe hier sind die Teile des Virus, die sehr, sehr schnell evolvieren,

00:01:06.72,00:01:09.05
und die blauen Teile evolvieren nicht sehr schnell.

00:01:09.15,00:01:12.64
Wenn Leute überlegen pan-virale Nachweisreagenzien zu erzeugen,

00:01:12.74,00:01:15.80
ist die schnelle Evolution üblicherweise das Problem,

00:01:15.90,00:01:18.27
weil wie soll man Dinge nachweisen wenn sie sich ständig ändern?

00:01:18.37,00:01:20.06
Aber die Evolution ist ein Gleichgewicht.

00:01:20.16,00:01:24.15
Da wo es schnelle Veränderungen gibt, gibt es auch Ultrakonservierung.

00:01:24.25,00:01:26.35
Dinge die sich fast nie ändern.

00:01:26.45,00:01:28.80
Also prüften wir dies ein bisschen sorgfältiger.

00:01:28.90,00:01:30.35
Ich werde ihnen jetzt Daten zeigen.

00:01:30.45,00:01:33.21
Das ist einfach Kram, den sie auf einem Computer am Desktop machen können.

00:01:33.31,00:01:37.67
Wir nahmen einen Haufen dieser kleinen Picornaviren, wie die gemeine Kälte, wie Polio u.s.w.

00:01:37.84,00:01:41.42
Und ich spaltete sie einfach in kleine Segmente auf, und so

00:01:41.52,00:01:44.24
nahm ich dieses erste Beispiel namens Coxsackie-Virus

00:01:44.34,00:01:46.00
und spalte es einfach in kleine Fenster.

00:01:46.10,00:01:50.61
Und ich färbe diese kleinen Fenster blau, wenn ein anderer Virus

00:01:50.71,00:01:54.10
eine identische Sequenz in seinem Genom mit diesem Virus gemein hat.

00:01:54.20,00:01:56.39
Diese Sequenzen bis hier her –

00:01:56.49,00:01:58.45
die übrigens nicht mal für Proteine kodieren –

00:01:58.55,00:02:01.78
sind fast gänzlich identisch unter allen.

00:02:01.88,00:02:03.87
Also könnte ich diese Sequenz

00:02:03.97,00:02:07.15
als Marker verwenden um ein breites Spektrum an Viren zu erkennen,

00:02:07.25,00:02:09.67
ohne etwas Individuelles erzeugen zu müssen.

00:02:09.77,00:02:13.72
Nun, hier drüben diese große Vielfalt; dort entwickeln sich Dinge sehr schnell.

00:02:13.82,00:02:17.57
Hier unten können sie langsamere Evolution sehen – weniger Vielfalt.

00:02:17.67,00:02:20.41
Nun, sobald wir zu dem, sagen wir,

00:02:20.51,00:02:22.40
Akuten-Bienen-Paralyse-Virus kommen –

00:02:22.50,00:02:24.41
wohl schlecht als Biene zu haben.

00:02:24.51,00:02:25.10
(Lachen)

00:02:25.20,00:02:29.18
Dieser Virus hat fast keine Ähnlichkeit mit dem Coxsackie-Virus,

00:02:29.28,00:02:32.10
aber ich kann ihnen versichern, dass die Sequenzen,

00:02:32.20,00:02:35.67
die unter diesen Viren auf der rechten Seite des Schirms am meisten konserviert sind,

00:02:35.77,00:02:38.25
bis hier her identische Regionen sind.

00:02:38.35,00:02:42.26
Und so können wir diese Regionen der Ultrakonservation (durch Evolution) umfassen –

00:02:42.36,00:02:45.40
wie diese Viren sich entwickelten, durch die Auswahl

00:02:45.50,00:02:51.72
von DNA- oder RNA-Elementen in diesen Regionen um sie auf unserem Chip als Nachweisreagenzien zu repräsentieren.

00:02:51.91,00:02:53.93
Okay, das taten wir auch, aber wie werden wir das tun?

00:02:54.03,00:02:58.07
Nun, für eine lange Zeit, seit ich in der Hochschule war, habe ich herumgebastelt

00:02:58.17,00:03:02.01
um DNA chips zu machen; das heißt DNA auf Glas zu drucken und das ist was sie hier gerade sehen.

00:03:02.11,00:03:05.17
Diese kleinen Salzflecken sind einfach DNA geheftet auf Glas,

00:03:05.27,00:03:09.61
und so kann ich Tausende von denen auf einen Glas-Chip geben und sie als Nachweisreagenzien verwenden.

00:03:09.71,00:03:13.93
Wir brachten unseren Chip zu Hewlett Packard und benutzten deren Rasterkraftmikroskop an einer dieser Stellen.

00:03:14.03,00:03:19.34
Und das ist was sie sehen. Sie können hier tatsächlich die flach-liegenden DNA-Stränge auf dem Glas sehen.

00:03:19.44,00:03:22.38
Was wir also tun, ist einfach DNA auf Glas zu drucken.

00:03:22.48,00:03:26.41
Kleine flache Dinger, und diese werden Marker für Pathogene sein.

00:03:26.64,00:03:30.13
Okay, ich baue kleine Roboter in Labors um diese Chips zu produzieren

00:03:30.23,00:03:32.96
und ich bin begeistert davon Technologie zu verbreiten.

00:03:33.06,00:03:37.13
Wenn sie genug Geld haben um ein (?) zu kaufen, dann können sie eines von diesen auch bauen.

00:03:37.23,00:03:40.96
Und so stellten wir eine detaillierte Anleitung ins Web, völlig gratis.

00:03:41.06,00:03:43.37
Mit, im Prinzip, serienmäßig produzierten Teilen,

00:03:43.47,00:03:46.37
können sie eine DNA Array-Maschine in ihrer Garage bauen.

00:03:46.47,00:03:49.71
Hier ist der Abschnitt über den hochwichtigen Notausschalter.

00:03:49.81,00:03:51.46
(Lachen)

00:03:51.56,00:03:54.62
Jede wichtige Maschine muss eine große, rote Taste haben.

00:03:54.72,00:03:58.32
Aber im Ernst, es ist sehr robust. Sie könnten eigentlich DNA-Chips

00:03:58.42,00:04:01.87
in ihrer Garage ziemlich rasch bauen und ein paar genetische Programme dekodieren.

00:04:01.97,00:04:03.22
Es macht eine Menge Spaß!

00:04:03.32,00:04:04.32
(Lachen)

00:04:04.42,00:04:05.84
Also was wir taten –

00:04:05.94,00:04:10.37
und das ist wirklich ein cooles Projekt – wir begannen einfach einen Respiratorisches-Virus-Chip zu erzeugen.

00:04:10.47,00:04:11.47
Ich sprach darüber.

00:04:11.57,00:04:14.72
Sie kennen die Situation wo sie zur Klinik gehen und nicht diagnostiziert werden?

00:04:14.82,00:04:19.46
Nun, wir gaben einfach alle Human-RSV-Viren auf einen Chip.

00:04:19.56,00:04:22.62
Und wir warfen noch Herpesvirus als Zugabe drauf. Ich mein, warum nicht?

00:04:22.72,00:04:25.36
Als Wissenschaftler stellen sie zuerst sicher, dass der Kram funktioniert.

00:04:25.46,00:04:28.53
Was wir also taten, ist einfach Gewebekulturzellen zu nehmen

00:04:28.63,00:04:30.76
um sie mit verschiedenen Viren zu infizieren.

00:04:30.86,00:04:34.48
Wir nehmen also dieses Zeug und markieren fluoreszierend die Nukleinsäure,

00:04:34.58,00:04:37.02
das genetische Material, dass aus diesen Gewebekulturzellen kommt –

00:04:37.12,00:04:38.40
meistens virales Zeug.

00:04:38.50,00:04:40.75
Und setzen es auf das Array um zu sehen ob es haften bleibt.

00:04:40.85,00:04:43.89
Nun, wenn die DNA-Sequenzen übereinstimmen, bleiben sie haften.

00:04:43.99,00:04:47.51
Also können wir Stellen ansehen und wenn sie aufleuchten wissen wir, dass da ein bestimmter Virus ist.

00:04:47.61,00:04:52.62
Das ist wie ein solcher Chip wirklich aussieht und die roten Stellen sind tatsächlich Signale, die vom Virus kommen.

00:04:52.72,00:04:56.56
Und jede Stelle repräsentiert eine andere Virusfamilie oder Spezies von Virus.

00:04:56.66,00:05:00.96
Das ist eine schwierige Art Dinge anzusehen, also werde ich sie als kleines Barcode kodieren,

00:05:01.06,00:05:04.87
gruppiert nach Familie, so dass sie die Ergebnisse auf sehr intuitive Art sehen können.

00:05:05.22,00:05:08.64
Was wir taten ist, wir nahmen Gewebekulturzellen und infizierten sie mit einem Adenovirus,

00:05:08.74,00:05:12.58
und sie können diesen kleinen, gelben Barcode neben Adenovirus sehen.

00:05:12.79,00:05:18.11
Und ebenso infizierten wir mit Parainfluenza 3, das ist ein Paramyxovirus – sie sehen einen kleinen Barcode hier.

00:05:18.21,00:05:23.62
Nun verwendenten wir einen RS-Virus. Das ist die Plage von Tagesstätten überall. Es ist wie (?).

00:05:23.72,00:05:25.40
(Lachen)

00:05:25.50,00:05:27.91
Sie können sehen, dass dieser Barcode

00:05:28.01,00:05:32.95
die selbe Familie ist, aber es ist verschieden von Parainfluenza 3, der dir eine schlimme Erkältung gibt.

00:05:33.05,00:05:36.46
Und so bekommen wir einzigartige Signaturen, ein Fingerabdruck für jeden Virus.

00:05:36.56,00:05:39.19
Polio und Rhino, die sind in der selben Familie, sehr nah zu einander.

00:05:39.29,00:05:41.55
Rhino ist der grippaler Infekt. Wir alle wissen was Polio ist.

00:05:41.65,00:05:44.25
Und sie können sehen, dass diese Signaturen deutlich sind.

00:05:44.35,00:05:47.13
Und der Kaposi-Sarkom-Herpesvirus

00:05:47.23,00:05:48.78
ergibt eine nette Signatur hier unten.

00:05:48.88,00:05:53.51
Also ist es nicht ein bestimmter Streifen oder so, der uns sagt wir haben einen Virus einer bestimmten Art hier.

00:05:53.61,00:05:57.38
Es ist der Barcode, der abschnittsweise das Ganze repräsentiert.

00:05:57.48,00:06:01.62
Also, ich kann den Rhinovirus sehen und hier ist die Vergrößerung des Rhinovirus – kleiner Barcode.

00:06:01.72,00:06:05.03
Aber was ist mit verschiedenartigen Rhinoviren? Wie kann ich wissen welchen Rhinovirus ich habe?

00:06:05.13,00:06:07.96
Es gibt 102 bekannte Varianten der gemeinen Kälte,

00:06:08.06,00:06:10.84
und es gibt nur 102, weil Leute es satt hatten sie zu sammeln.

00:06:10.94,00:06:12.70
Es gibt neue jedes Jahr.

00:06:12.80,00:06:16.53
Also, hier sind 4 verschiedene Rhinoviren und sie können sehen, selbst mit ihrem Auge –

00:06:16.63,00:06:20.84
ohne irgendwelche raffinierten Computer-Mustererkennungs-Software-Algorithmen –

00:06:20.94,00:06:24.32
dass sie jeden Barcode von einander unterscheiden können.

00:06:24.42,00:06:25.81
Nun, das ist sehr einfach,

00:06:25.91,00:06:28.83
weil wir die genetischen Sequenzen all dieser Rhinoviren kennen.

00:06:28.93,00:06:32.34
Und ich habe in der Tat einen Chip entworfen, vor allem um sie von einander unterscheiden zu können.

00:06:32.44,00:06:35.51
Aber was ist mit Rhinoviren, die noch nie einen Gensequenzer gesehen haben?

00:06:35.61,00:06:38.83
Wir kennen die Sequenz nicht. Zerr' sie einfach aufs Feld.

00:06:38.93,00:06:41.91
So, hier sind 4 Rhinoviren, über die wir noch nie etwas wussten.

00:06:42.01,00:06:44.66
Niemand hat sie jemals sequenziert, und sie können auch sehen,

00:06:44.76,00:06:48.70
dass sie einzigartige und unterscheidbare Muster kriegen. Sie können sich vorstellen eine Bibliothek aufzubauen,

00:06:48.80,00:06:52.14
wo es reale oder virtuelle Fingerabdrücke im Grunde aller Viren gibt.

00:06:52.24,00:06:54.85
Aber das, nochmals, ist ein Kinderspiel, nicht wahr?

00:06:54.95,00:06:58.64
Sie haben Gewebekulturzellen, da gibt es eine Tonne Viren. Was ist mit echten Menschen?

00:06:58.74,00:07:01.31
Sie können echte Menschen nicht kontrollieren, wie sie wohl wissen.

00:07:01.41,00:07:05.19
Sie haben keine Ahnung was jemand in einen Becher husten wird.

00:07:05.29,00:07:06.25
(Lachen)

00:07:06.35,00:07:08.63
Und es ist wahrscheinlich sehr komplex, nicht wahr?

00:07:08.73,00:07:13.17
Es könnte eine (?) Bakterie sein, es könnte ein (?) Virus ein, (?) sicherlich als genetisches Wirtsmaterial.

00:07:13.27,00:07:18.15
Wie gehen wir also damit um? Und wie machen wir die positive Kontrolle hier? Nun, es ist sehr einfach.

00:07:18.25,00:07:22.12
Das bin ich, während einer Nasenspülung, und die Idee ist,

00:07:22.22,00:07:25.17
infizieren wir Leute experimentell mit einem Virus.

00:07:25.27,00:07:28.19
Also wir – das ist übrigens alles RIV-genehmigt,

00:07:28.29,00:07:29.08
(Lachen)

00:07:29.18,00:07:34.09
sie wurden bezahlt – und wir infizieren im Grunde Leute mit dem gemeinen Kälte-Virus,

00:07:34.19,00:07:38.03
oder noch besser, holen wir Leute direkt aus der Notaufnahme.

00:07:38.13,00:07:41.32
Undefinierte, Gesellschafts-erworbene Infektionen der Atemwege.

00:07:41.42,00:07:43.62
Man hat keine Ahnung was durch die Tür spaziert.

00:07:43.72,00:07:46.40
Also beginnen wir zuerst mit der positiven Kontrolle,

00:07:46.50,00:07:50.82
wo wir wissen die Person war gesund; sie bekamen einen Schuss Viren in die Nase. Schauen wir was passiert.

00:07:50.92,00:07:52.89
Tag Null: nichts passiert.

00:07:52.99,00:07:56.70
Sie sind gesund und sauber. Es ist erstaunlich. Eigentlich dachten wir die Nasenwege dürften voll mit Viren sein,

00:07:56.80,00:08:00.24
selbst wenn du gesund herumlaufst; du bist ziemlich gesund. Wenn du gesund bist, bist du ziemlich gesund.

00:08:00.34,00:08:03.97
Tag Zwei: wir bekommen ein sehr robustes Rhinoviren-Muster

00:08:04.07,00:08:07.99
und es ist sehr ähnlich zu dem was wir im Gewebekultur-Experiment im Labor bekamen.

00:08:08.09,00:08:10.34
Das ist großartig! Aber nochmals, eine billige Nummer, nicht wahr?

00:08:10.44,00:08:13.12
Wir verpassten diesem Kerl eine Tonne Viren in die Nase, also

00:08:13.22,00:08:14.22
(Lachen)

00:08:14.32,00:08:16.71
wir wollten, dass es funktioniert, ich mein, er hatte wirklich eine Erkältung.

00:08:16.81,00:08:18.28
Also, ähm[br](Lachen)

00:08:18.38,00:08:20.87
was ist mit den Leuten, die auf der Straße herumlaufen?

00:08:20.97,00:08:23.69
Hier sind also zwei Individuen, repräsentiert durch ihre (?) ID-Codes.

00:08:23.79,00:08:27.01
Beide haben Rhinoviren, wir haben dieses Muster noch nie im Labor gesehen.

00:08:27.11,00:08:28.90
Wir sequenzierten einen Teil ihrer Viren.

00:08:29.00,00:08:31.79
Ihre neuen Rhinoviren hat noch nie jemand wirklich gesehen.

00:08:31.89,00:08:34.99
Erinnern sie sich, dass unsere evolutionär konservierten Sequenzen, die wir auf diesem Array verwenden,

00:08:35.09,00:08:38.81
uns erlauben selbst neuartige oder nicht-charakterisierte Viren nachzuweisen.

00:08:38.91,00:08:42.12
Weil wir das auswählen was durch die Evolution konserviert wird.

00:08:42.22,00:08:43.29
Hier ist ein weiterer Kerl.

00:08:43.39,00:08:47.48
Sie können das Diagnosespiel selbst spielen. Diese verschiedenen Blöcke stellen die verschiedenen Viren dar,

00:08:47.58,00:08:52.41
in dieser Paramyxovirus-Familie. So können sie einfach die Blöcke runtergehen und sehen was es signalisiert.

00:08:52.51,00:08:55.52
Hat kein Staupevirus (CDV), das ist wohl gut.

00:08:55.62,00:08:57.15
(Lachen)

00:08:57.75,00:09:02.63
Aber sobald sie zu Block Neun kommen sehen sie das Respiratorische Synzytial-Virus. Vielleicht haben sie Kinder?

00:09:02.73,00:09:06.85
Und sie können auch das verwandte Familienmitglied sehen, RSV B erscheint hier.

00:09:06.95,00:09:12.21
Das ist wunderbar. Hier ist noch ein Individuum. An zwei getrennten Tagen; wiederholte Besuche bei der Klinik.

00:09:12.31,00:09:15.00
Dieses Individuum hat Parainfluenza 1

00:09:15.10,00:09:20.00
und sie können hier drüben einen kleinen Streifen für Sendaivirus sehen. Das ist Mäuse-Parainfluenza.

00:09:20.10,00:09:22.55
Die genetische Verwandtschaft ist sehr eng dort.

00:09:22.65,00:09:25.09
Das macht eine Menge Spaß. Also bauten wir den Chip.

00:09:25.19,00:09:28.70
Wir erzeugten einen Chip, der alle bekannten Viren, die jemals entdeckt wurden, drauf hat.

00:09:28.80,00:09:32.29
Warum nicht? Alle Pflanzenviren, alle Insektenviren, alle Meeresviren.

00:09:32.39,00:09:36.83
Alles was wir aus der (?) bekommen, das ist die National Repository of Sequence.

00:09:36.93,00:09:39.27
Jetzt verwenden wir diesen Chip, und wofür verwenden wir es?

00:09:39.37,00:09:42.78
Nun, zuallererst, wenn man so einen großen Chip wie diesen hat, dann braucht man ein wenig mehr Informatik.

00:09:42.88,00:09:47.84
Also entwarfen wir ein System für automatische Diagnosen. Und die Idee ist, wir haben einfach

00:09:47.94,00:09:51.47
virtuelle Muster, weil wir niemals Proben aller Viren bekommen werden. Das wäre praktisch unmöglich.

00:09:51.57,00:09:52.97
Aber wir können virtuelle Muster bekommen

00:09:53.07,00:09:55.18
und sie mit unserem beobachteten Ergebnis vergleichen,

00:09:55.28,00:09:56.82
was eine sehr komplexe Mischung ist,

00:09:56.92,00:10:02.61
und eine Art von Punktzahl angeben wie wahrscheinlich es ist, dass das ein Rhinovirus ist oder so.

00:10:02.71,00:10:04.01
Und dies ist wie es aussieht.

00:10:04.11,00:10:08.32
Wenn du z.B. eine Zellkultur, die chronisch mit Papillom infiziert ist, verwendest,

00:10:08.42,00:10:10.39
dann bekommst du eine Computerausgabe,

00:10:10.49,00:10:13.63
und unser Algorithmus sagt es ist wahrscheinlich Papillom Typ 18.

00:10:13.73,00:10:17.92
Und das ist tatsächlich womit diese besonderen Zellkulturen chronisch infiziert sind.

00:10:18.02,00:10:19.90
Also lass uns etwas Schwierigeres tun.

00:10:20.00,00:10:22.60
Wir gaben einen Beeper in die Klinik. Wenn jemand erscheint

00:10:22.70,00:10:26.07
und das Krankenhaus weiß nicht was zu tun ist, weil sie es nicht diagnostizieren können, dann rufen sie uns.

00:10:26.17,00:10:28.27
Das ist die Idee. Und wir stellten das im Bay Area auf.

00:10:28.37,00:10:30.72
Also, dieser Fallbericht geschieht vor 3 Wochen.

00:10:30.82,00:10:36.28
Wir haben eine 28-jährige, gesunde Frau. Keine Reisevergangenheit. (?), raucht nicht, trinkt nicht.

00:10:36.38,00:10:38.24
Zehn Tage Fieber,

00:10:38.34,00:10:42.09
Nachtschweiß, blutiger Stuhl, sie hustet Blut, Muskelschmerzen.

00:10:42.19,00:10:44.04
Sie ging zur Klinik und die gaben ihr

00:10:44.14,00:10:45.29
Anti-Biotika.

00:10:45.39,00:10:49.51
Nicht wahr? Und schickten sie nach Hause. Sie kam zurück nach 10 Tagen Fieber.

00:10:49.61,00:10:54.28
Nicht wahr? Hat immer noch das Fieber und sie ist hypoxisch. Sie hat nicht viel Sauerstoff in ihren Lungen.

00:10:54.38,00:10:57.01
Sie machten einen CT-Scan. Eine normale Lunge

00:10:57.11,00:11:00.92
ist mehr oder weniger dunkel und schwarz hier. All das weiße Zeug, das ist nicht gut.

00:11:01.02,00:11:04.10
Diese Art von Baum- und Knospenbildung deutet auf Information.

00:11:04.20,00:11:06.92
Es gibt wahrscheinlich eine Infektion. Okay.

00:11:07.02,00:11:13.31
Also wurde die Patientin mit einer 3. Generation Ceftriaxone Antibiotika und Doxycyclin behandelt.

00:11:13.41,00:11:17.35
Und am Tage 3: es half nicht. Sie schritt fort zu akutem Versagen.

00:11:17.45,00:11:20.05
Sie mussten eingreifen und steckten einen Schlauch in ihren Hals

00:11:20.15,00:11:23.99
und sie begannen sie mechanisch zu beatmen. Sie konnte nicht mehr selbst atmen.

00:11:24.09,00:11:30.25
Was als nächstes tun? Keine Ahnung. Anti-Biotika wechseln. Also wechselten sie zu anderer Anti-Biotika: Tamiflu.

00:11:30.35,00:11:33.49
Es ist nicht klar warum sie dachten, dass sie die Grippe hatte, aber sie wechselten zu Tamiflu.

00:11:33.59,00:11:36.66
Und am Tage 6: im Grunde warfen sie das Handtuch.

00:11:36.76,00:11:39.79
Man macht eine offene Lungenbiopsie wenn man keine anderen Optionen hat.

00:11:39.89,00:11:42.54
Es gibt eine 8% Sterberate, wir machen einfach diese Prozedur.

00:11:42.64,00:11:47.09
Also – und was lernten sie daraus? Sie sehen gerade ihre offene Lungenbiopsie.

00:11:47.19,00:11:49.40
Ich bin kein Pathologe, aber man kann davon nicht viel ablesen.

00:11:49.50,00:11:55.93
Was man ablesen kann ist, da gibt es viel Schwellung, Bronchiolitis. Es war nicht aufschlussreich, das ist der Bericht des Pathologen.

00:11:56.03,00:11:59.65
Also, wonach untersuchten sie sie? Die haben natürlich ihre eigenen Tests.

00:11:59.75,00:12:04.63
Also testeten sie sie auf über 70 unterschiedliche Proben für jede Art von Bakterie und Fungus

00:12:04.73,00:12:09.74
und Virusprobe, die man vom Regal kaufen konnte: SARS, Metapneumovirus, HIV, RSV.

00:12:09.84,00:12:14.64
Alle davon. Alles kam negativ zurück. Tests im Wert von über $100.000.

00:12:15.04,00:12:19.15
Sie gingen bis zum Letzten für diese Frau. Und am 8. Krankenhaustag:

00:12:19.25,00:12:22.29
da riefen sie uns an. Sie gaben uns Endo(?).

00:12:22.39,00:12:25.31
Wissen sie, ein wenig Flüssigkeit aus dem Hals, aus dem Schlauch den sie da drinnen hatten.

00:12:25.41,00:12:27.84
Und sie gaben uns das, wir gaben es auf den Chip.

00:12:27.94,00:12:31.68
Was sahen wir? Nun, wir sahen Parainfluenza 4.

00:12:31.78,00:12:33.90
Was zur Hölle ist Parainfluenza 4?

00:12:34.00,00:12:37.24
Niemand testet auf Parainfluenza 4. Niemand interessiert es. In Wahrheit

00:12:37.34,00:12:40.66
ist es nicht mal viel sequenziert worden. Es ist nur ein klein wenig davon sequenziert.

00:12:40.76,00:12:43.30
Es gibt fast keine Epidemiologie oder Studien darüber.

00:12:43.40,00:12:48.41
Niemand würde es erwägen. Weil niemand einen Hinweis hatte, dass es respiratorisches Versagen verursachen kann.

00:12:48.51,00:12:50.60
Und warum ist das so? Nur Überlieferungen!

00:12:50.70,00:12:54.82
Es gibt keine Daten. Keine Daten um zu stützen ob es eine schwere oder leichte Krankheit verursacht.

00:12:54.92,00:12:58.50
Wir haben eindeutig den Fall einer gesunden Person, die zusammenbricht.

00:12:58.60,00:13:03.27
Okay. Das ist eines der Fallberichte. Ich werde ihnen zuletzt in den letzten zwei Minuten noch etwas erzählen,

00:13:03.37,00:13:05.71
das unveröffentlich ist. Es wird morgen herauskommen.

00:13:05.81,00:13:11.53
Es ist ein interessanter Fall wie sie diesen Chip benutzen könnten um Neues zu finden und neue Türen zu öffnen.

00:13:11.63,00:13:13.27
Prostatakrebs.

00:13:13.66,00:13:17.55
Ich muss ihnen nicht viele Statistiken über Prostatakrebs geben. Die meisten von ihnen kennen es bereits.

00:13:17.65,00:13:20.34
Dritt-führende Ursache der Krebstode in den V.S.

00:13:20.55,00:13:21.86
Eine Menge Risikofaktoren,

00:13:21.96,00:13:25.58
aber es gibt eine genetische Veranlagung zu Prostatakrebs.

00:13:25.68,00:13:28.51
Von vielleicht 10% der Prostatakrebsfälle

00:13:28.66,00:13:34.72
gibt es Leute, die dazu veranlagt sind. Und das erste Gen, das in Assoziationsstudien abgebildet wurde für

00:13:34.82,00:13:38.91
diesen früh-manifesten Prostatakrebs, war dieses Gen namens RNASEL. Was ist das?

00:13:39.01,00:13:41.70
Es ist ein antivirales Abwehr-Enzym.

00:13:41.80,00:13:45.65
Wir sitzen also herum und denken: warum würden Männer mit dieser Mutation,

00:13:45.75,00:13:49.94
ein Defekt im antiviralen Abwehrsystem, Prostatakrebs bekommen?

00:13:50.04,00:13:51.14
Es ergibt keinen Sinn.

00:13:51.24,00:13:53.54
Außer wenn es einen Virus gibt.

00:13:53.64,00:13:54.64
Also,

00:13:54.90,00:13:58.41
wir gaben Tumore – und jetzt haben wir über hundert Tumore –

00:13:58.51,00:14:02.69
auf unser Array und wir wissen wer einen Defekt in RNASEL hat und wer nicht.

00:14:02.79,00:14:05.37
Und ich zeige ihnen das Signal von diesem Chip hier,

00:14:05.47,00:14:08.54
und ich zeige es ihnen für einen Block von retroviralen (?).

00:14:08.64,00:14:11.09
Und was ich ihnen über dieses Signal sagen kann ist,

00:14:11.19,00:14:16.40
dass Männer, die eine Mutation in diesem antiviralen Abwehr-Enzym und einen Tumor haben,

00:14:16.50,00:14:22.57
oft, zu 40%, eine Signatur haben, die einen neuen Retrovirus erkennen lässt.

00:14:22.90,00:14:24.55
Okay, das ist ziemlich wild.

00:14:24.65,00:14:27.68
Was ist es? Also klonen wir den ganzen Virus.

00:14:27.78,00:14:32.93
Zunächst sag ich ihnen, dass unsere automatische Prognose uns sagte es wäre sehr ähnlich zu einem Mäusevirus.

00:14:33.06,00:14:36.01
Aber das sagt uns nicht viel. Also klonten wir tatsächlich das Ganze.

00:14:36.11,00:14:38.24
Und das virale Genom, das ich ihnen genau hier zeige;

00:14:38.34,00:14:42.19
es ist ein klassischer Gammaretrovirus, aber es ist sehr neu. Niemand hat es zuvor jemals gesehen.

00:14:42.29,00:14:46.33
Der naheste Verwandte kommt tatsächlich von Mäusen, und so könnten wir es

00:14:46.48,00:14:52.10
xenotropischer Retrovirus nennen, weil es neben Mäusen auch andere Spezies infiziert.

00:14:52.63,00:14:56.78
Und dies ist ein kleiner phylogenetischer Baum, um zu sehen wie es mit anderen Viren verwandt ist.

00:14:56.88,00:14:59.18
Und dann haben wir es für viele Patienten gemacht,

00:14:59.28,00:15:01.58
und wir können sagen, dass sie alle unabhängige Infektionen sind.

00:15:01.68,00:15:04.14
Sie alle haben den selben Virus, aber sie sind unterschiedlich genug,

00:15:04.24,00:15:07.27
dass es Grund genug ist zu glauben, dass sie unabhängig erworben wurden.

00:15:07.37,00:15:10.29
Ist es wirklich im Gewebe? Wir kommen zu diesem hier. Ja.

00:15:10.39,00:15:13.21
Wir nehmen Scheiben dieser Tumorgewebe-Biopsien

00:15:13.31,00:15:15.63
und verwendeten Material um diesen Virus tatsächlich zu lokalisieren,

00:15:15.73,00:15:19.11
und wir finden Zellen hier mit Viruspartikeln in ihnen.

00:15:19.21,00:15:23.42
Diese Kerle haben wirklich den Virus. Verursacht dieser Virus Prostatakrebs?

00:15:23.52,00:15:26.99
Nichts was ich sage deutet Kausalität an. Ich weiß es nicht.

00:15:27.09,00:15:29.47
Hängt es zusammen mit Ontogenese? Ich weiß es nicht.

00:15:29.57,00:15:33.04
Trifft es zu, dass diese Kerle einfach anfälliger für Viren sind?

00:15:33.14,00:15:35.63
Könnte sein. Und es könnte nichts mit Krebs zu tun haben.

00:15:35.73,00:15:39.58
Aber jetzt ist es eine Tür. Wir haben starke Assoziationen zwischen dem Dasein dieses Virus

00:15:39.68,00:15:42.69
und einer genetischen Mutation, die mit Krebs in Zusammenhang gebracht wird.

00:15:42.79,00:15:44.88
Das ist wo wir gerade sind. Also,

00:15:44.98,00:15:48.37
es tun sich mehr Fragen auf als beantwortet werden, befürchte ich.

00:15:48.47,00:15:50.36
Aber das ist was, verstehen sie, worin die Wissenschaft sehr gut ist.

00:15:50.46,00:15:53.41
All das wird von Leuten im Labor gemacht, das meiste ist nicht mein Verdienst.

00:15:53.51,00:15:54.99
Das ist eine Zusammenarbeit zwischen mir und Don.

00:15:55.09,00:15:59.42
Und das ist der Kerl, der das Projekt in meinem Labor begann, und das ist der Kerl, der das Prostatazeug macht.

00:15:59.52,00:16:00.66
Vielen Dank!

